### ISSUE TITLE
Grammar is Secondary

### ISSUE THREAD

**Issue by SumanthLazarus** [CodingTrain/Rainbow-Poem#1643]
#1642 mentions that grammar needs to be altered in poem 'Chicago'; however I would like to point out that rules of grammar can be bent to benefit artistic creativity in art forms such as poetry and others. [This article justifies the same](https://www.writingforward.com/poetry-writing/breaking-grammar-rules-in-poetry-writing).
Please don't mind the earlier point in the issue @akraus53 .

**Comment by akraus53** [comment]
Noted! Grammar will stay horrible in the whole repo!
