### ISSUE TITLE
Need to add "And the pony" 

### ISSUE THREAD

**Issue by herndonj** [CodingTrain/Rainbow-Poem#17]
Need to add the phrase "and the pony" at the end of the poem to keep things parallel.

**Comment by RainbowCoder** [comment]
Due to multiple pull requests, this branch now has conflicts, will be using these and other issues to show how to rebase / resolve conflicts soon!

**Comment by akraus53** [comment]
Choo Choo, fellow CodingTrain viewer!
This issue will be closed because its no longer relevant or was supposed to be fixed by a pull request, which was denied! Thanks for your understanding! Feel free to add a new contribution if you want to.
