### ISSUE TITLE
There are not enough horques in this poem

### ISSUE THREAD

**Issue by koshaughnesseyRye** [CodingTrain/Rainbow-Poem#1915]
This poem needs more horques.

**Comment by shiffman** [comment]
Hi @koshaughnesseyRye!!! 🎶

**Comment by koshaughnesseyRye** [comment]
Hi Shiffy!  Thanks for approving the addition of the horque.  I recently learned to spell that online:-) . Thinking of you while watching your gitHub for poets vids.  Thanks for these!  S
