### ISSUE TITLE
Need help (seriously)

### ISSUE THREAD

**Issue by belgiancoder** [CodingTrain/Rainbow-Poem#424]
hello,
I typed this in the terminal
` git commit -a -m "added belgian"`
Directory seems correct (clone too)
`/Users/benoit/Desktop/Rainbow-Poem`
It didn't work
Also, I don't understand what the difference between 'push' and 'commit' is.

**Comment by belgian-coder** [comment]
and what is the difference between 'commit' and 'merge pull request'.
I watched @shiffman 's videos over and over but i can't get it.
