### ISSUE TITLE
refer to some writers of poem rainbow

### ISSUE THREAD

**Issue by Aman-Godara** [CodingTrain/Rainbow-Poem#449]
why don't we look out for the works of some prominent writers who had written some poems on RAINBOW. And please accept this pull request #448  and #450 .

**Comment by Godara-aman** [comment]
https://goo.gl/images/XDtivk            here is a website with a beautiful poem on rainbow.

**Comment by Godara-aman** [comment]
as i didn't find get any writer of the poem rainbow  so i think that this fixes #449 .
