### ISSUE TITLE
Needs more gorillas

### ISSUE THREAD

**Issue by Cfhhunt** [CodingTrain/Rainbow-Poem#669]
This poem only mentions one gorilla.

**Comment by 654321ignition** [comment]
why the issue not closed? you have fixed it. @Cfhhunt

**Comment by MadeInPierre** [comment]
I think only contributors of repo admins can make the issue toggle to closed, right?

**Comment by akraus53** [comment]
### Hi fellow coder!
Thank you very much for contributing. 
If you want this change to be merged into the master branch, please create a pull request.

*Have a nice day!*
