### ISSUE TITLE
I don't understand japanese :(

### ISSUE THREAD

**Issue by rainbowsprinkles132** [CodingTrain/Rainbow-Poem#716]
I don't understand what's written

fa7d7dc8d8e7d0847014dbc835b9f9cbee75d3c9#diff-e83df219bdd2aed1d909f0403f756193

**Comment by konsoul** [comment]
@rainbowsprinkles132 

Rough Google Translation :

Rainbow
Grime
Blue
yellow
Beautiful
It 's not beautiful.
Compare with you
